### ISSUE TITLE
Weekly schedule Class error

### ISSUE THREAD

**Issue by Macacosky** [Re-Volt-America/RVA#98]
In English and Spanish translations of the weekly schedule page the Class "Random" of Random Cars appears as "Unknown", or "Desconocido".
This week's weekly schedule: https://rva.lat/weekly_schedules/66413c2e8a6ce35c64c985aa
Take a look on Wednesday.
There are some translations missing on Spanish (Spain flag) for the page in the Schedule (Days and classes).

**Comment by EstebanMz** [comment]
I've already asked about the matter on [Crowdin](https://crowdin.com/editor/rva/96/enus-escl?view=comfortable&filter=basic&value=0#8618), the text will stay as it is for now because it's a key than may be reused somewhere else.
![imagen](https://github.com/Re-Volt-America/RVA/assets/19150477/e739427f-b21c-432d-990a-af25735c5891)

About Spanish (Spain) translation, I'm aware that only a bit more than half of the strings have been translated. I recommend to change your language to Spanish (Chile) as it's been completely translated.

**Comment by BGMP** [comment]
Resolved by https://github.com/Re-Volt-America/RVA/commit/f0c7219517253782253b4d353aab4dbf326b5f81
